version: '3.8'

services:
  client:
    image: cvcharanraj/cloudsecure-client:latest
    container_name: cloudsecure-client
    environment:
      - REACT_APP_API_URL=http://cloudsecure-server:3031
      - NODE_ENV=production  # Use production for the built React app
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  server:
    image: cvcharanraj/cloudsecure-server:latest
    container_name: cloudsecure-server
    ports:
      - "3031:3031"  # Match the port in server.js
    depends_on:
      - redis-service
      - mongo-service
    environment:
      - MONGODB_URI=mongodb://mongo-user:mongo-password@mongo-service:27017/cloudsecure?authSource=admin
      - REDIS_URL=redis://redis-service:6379
      - PORT=3031
      - NODE_ENV=production  # Use production
      - JWT_SECRET=${JWT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3031/api-docs"]  # Check Swagger endpoint
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongo-service:
    image: mongo:latest
    container_name: mongo-service
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-user
      - MONGO_INITDB_ROOT_PASSWORD=mongo-password
      - MONGO_INITDB_DATABASE=cloudsecure
    ports:
      - "27017:27017"  # Remove in production if not needed
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis-service:
    image: redis:alpine
    container_name: redis-service
    ports:
      - "6379:6379"  # Remove in production if not needed
    restart: always
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: